project_id = "qbvlgzmivdycuocvcoxy"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.toss-config]
    verify_jwt = false
  [functions.download-extension]
    verify_jwt = false
  [functions.kakao-auth]
    verify_jwt = false
  [functions.identity-links]
    verify_jwt = false
